### ISSUE TITLE
Software list doesn't display all installed software of type apt

### ISSUE THREAD

**Issue by zhong-ys** [thin-edge/tedge-demo-container#79]
The software list is only showing part of the result of 'apt list'. 
<img width="960" alt="Screenshot 2024-05-02 at 15 03 45" src="https://github.com/thin-edge/tedge-demo-container/assets/73714994/7b1389e0-45e1-46f5-8d79-992f303f3c05">

After installing a new software, it won't listed in the Installed software list, even if the installation was succeed. 

Restart containers cannot solve this.

**Comment by reubenmiller** [comment]
@zhong-ys There is filtering activated on the apt package list.

You can see which packages are included by running the following command:

```sh
tedge config get apt.name
```

```sh
(tedge|c8y|python|wget|vim|curl|apt|mosquitto|ssh|sudo).*
```

The reason for the filtering is that without it, you get way too many uninteresting packages. Currently only an inclusive filter is supported but there is a ticket for exclusive filtering (https://github.com/thin-edge/thin-edge.io/issues/2848)...this will make it easier to exclude libraries and kernel modules (as this makes up about 90% of the installed packages list).

So for now, you can either just remove the default apt filter, or extend it to your liking.

**Comment by reubenmiller** [comment]
This is where the default value is coming from (for the systemd enable container): https://github.com/thin-edge/tedge-demo-container/blob/f0ce795f501dd8cf8b7ae8c61f0dfaa31df41fa0/images/common/config/tedge.toml#L15

**Comment by zhong-ys** [comment]
Thank you for your detailed explanation! I will close this issue.
